### ISSUE TITLE
Select call has no fulfilment object

### ISSUE THREAD

**Issue by techframewirk** [beckn/protocol-specifications#138]
In use cases where the parameters of fulfilment is required for providing a quote, the fulfilment object should be part of the select call as well. 

Examples : 
- BPP provides multiple fulfilment options (express, standard, store pickup etc) with different pricing logic.
- Hospitality industry where the start and end date of fulfilment would be essential for providing the quote.

So I propose the fulfilment object should also be a part of the select call.

**Comment by beckn-dev** [comment]
Agreed @techframewirk. The `select`, `init` and `confirm`, `status` and `cancel` actions must allow the complete `Order` object to be transmitted and let the network participant decide what fields are required for each action. Kindly raise a PR for the same.

**Comment by core-wg-admin** [comment]
@techframewirk any update on this?

**Comment by techframewirk** [comment]
@core-wg-admin Changes on select might be a breaking change. Evaluating the same.

**Comment by techframewirk** [comment]
In `select` and `init` I have adding the complete order object. In `confirm` the full order object is referred already. 

There is no breaking impact here. But if we look at the specs, I feel it makes it less obvious what these calls will be used for looking at the specs. As in select, init etc will all have the same order object.  This is not a blocker but still I feel something we may need to consider.

In `cancel` and `status` the order is referred to using the order id. Should this be changed? I don't see any use cases for this.

**Comment by techframewirk** [comment]
Closing as PR has been merged.
