### ISSUE TITLE
Currently the Authorization and Proxy-Authorization headers headers use space as separator  

### ISSUE THREAD

**Issue by techframewirk** [beckn/protocol-specifications#141]
According to existing standards that can be found in this [IETF document](https://tools.ietf.org/id/draft-cavage-http-signatures-12.html) instead of spaces, commas should be used as the separator.

**Comment by core-wg-admin** [comment]
Acknowledged. Can you please raise a PR against this?

**Comment by techframewirk** [comment]
Created new PR #149 and linked it in issue #119 as PR #115 is based on 0.9.1-draft-03. Hence created new PR with base 0.9.3-draft. 

Closing this issue as this issue has been fixed and merged. Need to review and merge #149 to close issue #119.
