### ISSUE TITLE
Algorithm to be used for signing

### ISSUE THREAD

**Issue by techframewirk** [beckn/protocol-specifications#142]
The algorithm mentioned in the example Authorization header is xed25519 while current implementations are using ed25519. Should this be updated?

**Comment by core-wg-admin** [comment]
Yes. Just to be clear, the algorithm is `ed25519` and not `ed2551` as per your comment.

**Comment by techframewirk** [comment]
> Yes. Just to be clear, the algorithm is `ed25519` and not `ed2551` as per your comment.

Corrected the typo.

**Comment by techframewirk** [comment]
Closing issue.
