### ISSUE TITLE
Governance.md uses text from the OAI Spec

### ISSUE THREAD

**Issue by ghane** [beckn/protocol-specifications#167]
We are copying, verbatim, large chunks of the OAI spec.

The OAI spec is licenced under Apache-2.  That requires copyright notices to be preserved.   Please see Section 4 of https://github.com/OAI/OpenAPI-Specification/blob/main/LICENSE

We can use, adapt, copy the text, but must attribute it appropriately.

**Comment by core-wg-admin** [comment]
Noted. Due attribution to Open API 3.0 Spec shall be provided.

**Comment by techframewirk** [comment]
@ghane @core-wg-admin Have merged the changes. Let me know if this is not enough and the issue needs to be reopened.
