### ISSUE TITLE
Glossary and architecture diagram 

### ISSUE THREAD

**Issue by chainhead** [beckn/protocol-specifications#193]
---

Name: Beckn
Title: "Glossary and architecture diagram"
Labels: C4GT Community

---

## Description

It would help, if there was a glossary for various acronyms and any other terms.

An architecture diagram covering various entities with an overlay of beckn network would help clarify the vision.

## Expected Outcome

Change in Schema 

---

### Project

Beckn

### Organization Name:

Beckn Open Collective

### Domain

Others

### Tech Skills Needed:

Open API 3.0
Beckn Protocol

### Mentor(s)

Ravi Prakash

### Complexity

Low

### Category

Documentation

### Sub Category

Support

**Comment by core-wg-admin** [comment]
![Beckn Architecture](https://user-images.githubusercontent.com/52468749/150474423-eb0f6227-770c-492b-b84b-e4e8f57d3fe4.png)

**Comment by core-wg-admin** [comment]
@bharath-ganapathy can we start listing the terms that frequently occur in beckn terminology?

Later we cab compile the terms into a doc.

**Comment by techframewirk** [comment]
**WIP**

- **Transaction Layer** 

The Transaction layer consists of Beckn Application Platforms (BAPs), on one side, Beckn Provider Platforms (BPPs), on the other, and Beckn Gateways (BGs), in-between them. BAPs search and find consumer services, BPPs fulfill them, and BGs ensure the discoverability of the BPPs (by the BAPs) on the network and the application any compliance and regulatory policies.

- **Beckn App Platforms (BAPs)**

A Beckn Application Platform (BAP) is a server-side infrastructure which captures consumers’ requests via its UI applications, converts them into Beckn-compliant schemas and APIs at the server side, and fires them at the network. BAPs are the initiator of the transaction and have the flexibility to communicate with multiple networks and integrate the responses from these networks into a bundled shopper experience.

- **Beckn Provider Platforms (BPPs)**

A Beckn Provider Platform (BPP) is a server-side infrastructure which implement the supply logic and present it in the form of a Provider Catalog. The BPP can be a single provider with a Beckn API implementation or an aggregator of merchants — this, of course, depends upon the logic of the particular implementation.

- **Beckn Gateways (BGs)**

A Beckn Gateways (BG) is an extremely lean and stateless routing servers. The purpose of this infrastructure is to route requests from the BAP to the BPPs, and from the BPPs back to the BAP. The BG takes a request from the BAP, determines to which BPPs the message needs to forwarded and multicasts the message to them.

- **Registry Infrastructure layer**

The Registry Infrastructure layer comprises a network of open registries that store detailed information about every network participant. The registries are maintained by entities called “Registration Platforms”.

- **Registration Platform**

The Registration Platform is a trusted entity that maintains the registry of the participants on the network. Registration Platforms can be formed by the participants of the network or by a public authority; this depends on nature of the network. A network can have more than one such registration platform, all operating by the same rules.

- **Registrant**

Any business or non-profit entity that wants its platform to be listed on the Registry. To be listed, the registrant must submit relevant credentials to the Registration Platform. A registrant can apply to be a Beckn Application Platform (BAP), Beckn Provider Platform (BPP), or Beckn Gateway (BG) or any other role allowed in the network.

- **Subscriber**

After the registrant is approved by the Registration Platform, it is listed on the registry with INITIATED status. From this moment on, the entity being registered in no longer a registrant and becomes a subscriber. The subscriber status gives the entity the right to perform transactions on the network.

**WIP**

**Comment by chainhead** [comment]
What personae interface with the entities listed above?

**Comment by chainhead** [comment]
Bump.

**Comment by emmayank** [comment]
@ravi-prakash-v , as discussed closing this thread because whole documentation structured is being revised.
