### ISSUE TITLE
Description for SubscriberAuth, GatewaySubscriberAuthNew should be changed to remove BLAKE-512 from signature

### ISSUE THREAD

**Issue by BLR-0118** [beckn/protocol-specifications#196]
Description for SubscriberAuth is as follows:
Authorization : Signature keyId="{subscriber_id}|{unique_key_id}|{algorithm}",algorithm="ed25519",created="1606970629",expires="1607030629",headers="(created) (expires) digest",signature="Base64(BLAKE-512(signing string))"

digest is already a BLAKE-512 hash of the request body. Hence signature should just be **Base64(signing string)**

same also applies to GatewaySubscriberAuth, GatewaySubscriberAuthNew

**Comment by emmayank** [comment]
Hi @ravi-prakash-v 

This Issue seems to be resolved, can you please confirm and close the issue.

Thanks

**Comment by emmayank** [comment]
Closing this issue, as it is resolved
