### ISSUE TITLE
Payment object should include collected_by attribute

### ISSUE THREAD

**Issue by BLR-0118** [beckn/protocol-specifications#197]
"[Payment on Beckn Enabled Networks](https://github.com/beckn/protocol-specifications/blob/master/docs/protocol-drafts/BECKN-RFC-002-Payments-On-Beckn-Enabled-Networks.md)" uses the "collected_by" attribute in Example 1. This attribute needs to be added to the **Payment** object

**Comment by core-wg-admin** [comment]
Noted. Please submit a PR to 0.9.4-draft

**Comment by BLR-0118** [comment]
@core-wg-admin - this is the issue I was talking about today

**Comment by emmayank** [comment]
Hi @ravi-prakash-v

This Issue seems to be resolved, can you please confirm and close the issue.

Thanks

**Comment by emmayank** [comment]
Closing this issue, as it is resolved
