### ISSUE TITLE
Value of method in example 3 of "Payments on Beckn Enabled Networks" should be "HTTP/POST"

### ISSUE THREAD

**Issue by BLR-0118** [beckn/protocol-specifications#215]
Example 3 shows transfer to payment gateway https endpoint. In this example, value of method should be "HTTP/POST", not "PAYTO"

**Comment by core-wg-admin** [comment]
@BLR-0118 thanks for pointing that out. @techframewirk kindly resolve the issue.

**Comment by core-wg-admin** [comment]
@BLR-0118 can you please raise a PR?

**Comment by BLR-0118** [comment]
Additional issues fixed here (for examples 1, 2, 3):
1. Changed "method" to "tl_method" as per the spec
2. Changed "PAYTO" to "UPI" for example 2 (as per definition of Payment object)

**Comment by emmayank** [comment]
Hi @ravi-prakash-v

This Issue seems to be resolved, can you please confirm and close the issue.

Thanks

**Comment by emmayank** [comment]
Closing this Issue, as it seems to be resolved.
