### ISSUE TITLE
Privacy by design & Data Governance

### ISSUE THREAD

**Issue by srikanthlogic** [beckn/protocol-specifications#22]
I see [GOVERNANCE.md](https://github.com/beckn/protocol-specifications/blob/master/GOVERNANCE.md) is an empty file and from the architecture, it looks like Beckn gateways will aggregate location-aware, identity aware requests & responses (that may / may not fulfilled) across consumer facing beckn apps for a range of services. Given this, there needs to be an effort to look into aspects of PbD. An off the hand example - I don't think it makes any sense to pass on dob in person.json for a ride request, while it may be ostensibly necessary in some contexts (alcohol delivery - Even there a simple age check should do). 

1. Since the core is common to expandable set of services, should there be some refactoring for PbD ?

2. Can there be validators that restrict collection of data for specific use cases while using the common core - if the common core is to remain unaltered?

It would also help if more clarity is provided on what "surveillance services" mean in the below context.

![image](https://user-images.githubusercontent.com/126862/87845037-e77a4180-c8e0-11ea-9c62-ec0ec745c86b.png)

**Comment by fahadsuhaib** [comment]
Very good points, This should be done. I would say get minimum data from the customer to start with. For the ALCO delivery perspective, the business has to ensure by getting some kind of ID before the order is accepted itself? To do exactly what you are saying it will go into using Blockchain like systems, but thats an overkill.

**Comment by beckn-dev** [comment]
Regarding your question on governance, the beckn specification evolves through an open community contribution process. To know more about the open community of beckn please visit - https://beckn.org/opencommunity/. 

Regarding your question on the Beckn Gateway, the BG does not act as an aggregator but merely a broadcaster of search requests and post-search transactions does not go through the Beckn Gateway. It itself relies on an open registry to identify services and broadcast to. It only provides search request routing from Beckn Apps to Beckn Providers and vice versa. The search packet only contains search parameters and does not carry any customer information. The Beckn Gateway has no knowledge of the end customer.

Beckn protocol is just a set of open standards and specifications that is publicly available and it is for interoperable digital commerce transactions. The trademark of the "beckn" brand is to avoid misuse of the brand mark. The trademark classes which beckn brand mark is registered also include class 9 that mentions Privacy Protection and class 42 that mentions interoperability protocol. It requires harmonious reading of all classes to understand how beckn brand is registered to avoid any misuse of the brand mark Beckn. There are no standards related to surveillance in Beckn.
