### ISSUE TITLE
Fix all schema descriptions as per correct definitions. 

### ISSUE THREAD

**Issue by ravi-prakash-v** [beckn/protocol-specifications#231]
---

Name: Protocol Specifications
Title: "Fix all schema descriptions as per correct definitions."
Labels: C4GT Community, Bug, Documentation, Specification Release

---

## Description

A lot of the schema definitions are either vague or outdated. We need to fix all descriptions ASAP.

## Expected Outcome

-Fix all schema descriptions as per correct definitions 

---

### Project

Beckn

### Organization Name:

Beckn Open Collective

### Domain

Others

### Tech Skills Needed:

Open API 3.0
Beckn protocol

### Mentor(s)
Ravi Prakash

### Complexity

Medium

### Category

Bug, Documentation

### Sub Category

Support, Question, Research, Reproducible

**Comment by core-wg-admin** [comment]
@bharath-ganapathy @techframewirk this has to be closed before March 15th, 2022 so that we can include it in the next release.

**Comment by monishkajha17** [comment]
@ravi-prakash-v  Can you please elaborate this issue more, schema for what? or any thing existing which needs polishing can you specify that please.

**Comment by emmayank** [comment]
Closing this issue, as it is already resolved as part of v1.x release.
