### ISSUE TITLE
UI/UX Specifications for location-aware apps

### ISSUE THREAD

**Issue by Goutam192002** [beckn/protocol-specifications#24]
I'm aware beckn currently provides only API specifications for enabling location aware applications.
This is more of a feature request.

Can we add a design (UI) specification for these apps? 
This will enable designers to contribute to open-source and businesses will be able to use this as a starting point and build their customizations on top of it?

Would be happy to contribute on this part.

**Comment by beckn-dev** [comment]
@Goutam192002 beckn is a server to server protocol and does not have UI specificaton. However, there are reference applications that are in the pipeline that designers can contribute to. Will keep you posted.
