### ISSUE TITLE
The format of the `id` which is a property of `Item` is invalid.

### ISSUE THREAD

**Issue by AyushAgrawal25** [beckn/protocol-specifications#243]
File path: `core\v0\api\core.yaml`.
`Item` is present inside the `schemas` which inside the `components` have a property `id` whose format is `#/components/schemas/Item/properties/id` which is actually the address to the `id` property only.

**Comment by core-wg-admin** [comment]
Ah! it seems to be an infinite reference loop. Can you just make it as `type: string` and submit a PR to the `draft` branch of the spec?
