### ISSUE TITLE
/on_support | Getting "500 Internal Server error", and unknown phone format error"

### ISSUE THREAD

**Issue by AdithyaRamakrishna** [beckn/protocol-specifications#246]
**Actual Result**:- "message": "Error: unknown format \"phone\" is used in schema at path \"#/properties/body/properties/message/properties/phone\"

**Proof Link**:- _https://drive.google.com/drive/folders/1C_SrLtuZ6vuBgSWZ944B7N7f18rc7Jr0?usp=sharing_

**curl**:-
curl --location --request POST 'https://staging.bap.protocolserver.becknprotocol.io//on_support' \
--header 'Authorization: Signature keyId="ty.test.subscriber|ty.test.subscriber.k1|ed25519",algorithm="ed25519",created="1649403626",expires="1649403636",headers="(created) (expires) digest",signature="dD5DXuusyxQNA5tvddAiew2bp/ceUavCJMLF+0ipkJB2lon21cgvGxl1CbgxHp7vr2Wq56SULv1VEAJ4u9/JAQ=="' \
--header 'Content-Type: application/json' \
--data-raw '{
    "context": {
        "domain": "nic2004:52110",
        "country": "IND",
        "city": "STD:080",
        "action": "support",
        "core_version": "0.9.3",
        "bap_id": "qa.api.box.beckn.org",
        "bap_uri": "https://7818-27-62-144-87.ngrok.io/protocol/",
        "bpp_id": "ty.test.subscriber",
        "bpp_uri": "https://beckn.free.beeceptor.com",
        "transaction_id": "992e66d4-b99e-4da3-9758-2783a1af7513",
        "message_id": "825a9855-67d1-45df-adf8-4bf6d297f084",
        "ttl": "PT1M",
        "timestamp": "2022-04-08T08:16:57.317Z",
        "key": "ty.test.subscriber.k1"
    },
    "message": {
        "phone": "+919538257532",
        "email": "user@example.com",
        "uri": "https://free.beeceptor.com"
    },
    "error": {
        "type": "CONTEXT-ERROR",
        "code": "958",
        "path": "adithya/user",
        "message": "thanks for your support"
    }
}'

**Comment by core-wg-admin** [comment]
@AdithyaRamakrishna if it is a run-time issue, I suggest contacting the provider of the endpoint i.e "https://beckn.free.beeceptor.com/".

This forum is for discussion issues with the specification and not its run-time implementations.
