### ISSUE TITLE
OAS3 Validation: allOf must be a non-empty array of schemas

### ISSUE THREAD

**Issue by ashok2ashok** [beckn/protocol-specifications#320]
Name: Protocol Specifications
Title: "OAS3 Validation: allOf must be a non-empty array of schemas"
Labels: C4GT CommunitY

---

## Description

OAS3 Validation of the Core API schema shows a lot of validation warnings - all of them around allOf usage:
allOf must be a non-empty array of schemas

![Screenshot 2022-10-04 at 9 09 44 AM](https://user-images.githubusercontent.com/646649/193729712-9c7e3a61-659e-4f58-a9da-084610c1470f.png)

https://editor-next.swagger.io/?url=https://raw.githubusercontent.com/beckn/protocol-specifications/draft/core/v0/api/core.yaml
or
https://editor-next.swagger.io/?url=https://github.com/beckn/protocol-specifications/blob/release-1.x-review/core/v0/api/core.yaml

---

### Project

Beckn

### Organization Name:

Beckn Open Collective

### Domain

Others

### Tech Skills Needed:

Open API 3.0
Github actions
JSON

### Mentor(s)

Ravi Prakash

### Complexity

Medium

### Category

Bug

### Sub Category

Needs Reproduction

**Comment by dgaedcke** [comment]
I'm having the same problem ... and my (auto-gen) syntax looks like below.
Is this a problem or just a warning?
`          "userInterval": {
            "default": null,
            "nullable": true,
            "allOf": [
              {
                "$ref": "#/components/schemas/IntervalMessage"
              }
            ]
          },`

**Comment by Skeeve** [comment]
Same here with "oneOf": `oneOf must be a non-empty array of schemas`

```yaml
openapi: 3.0.3
info:
  title: Test
  version: "1.2.alpha2"
paths:
  /notifications:
    get:
      summary: Get the current active notifications per brand or sender
      responses:
        '200':
          description: …
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/notifications_sender"
                  - $ref: "#/components/schemas/brand_info"
                  - $ref: "#/components/schemas/just_a_number"
components:
  schemas:
    notifications_sender:
      type: object
      properties:
        amount:
          type: integer
        alert_status:
          type: string
          pattern: ^(OK|WARNING|ALARM)$
      required:
        - amount
        - alert_status
    brand_info:
      type: array
      items:
        type: object
        properties:
          amount:
            type: integer
          alert_status:
            type: string
            pattern: ^(OK|WARNING|ALARM)$
          brand:
            type: string
            minLength: 1
            maxLength: 255
        required:
          - amount
          - brand
    just_a_number:
      type: integer
```

**Comment by emmayank** [comment]
Hi @ashok2ashok , @dgaedcke 

The Issue seems to be resolved in v1.x release. closing this for now, feel free to reopen if needed.

Thanks
emmayank
