### ISSUE TITLE
Typo in readme file | Improvement

### ISSUE THREAD

**Issue by deeqakkk** [beckn/protocol-specifications#348]
---
### What?
I was reading the documentation of repo, and found a typo in the it.

### Why?
It should be fixed because it typo might create or reduce the trust that users have on the protocol along with authenticity.

### How?
It can be simply fixed by simplying changing a word with correct grammar.

### Screenshot
![image](https://user-images.githubusercontent.com/78724676/219909163-a987aa45-c5c7-421f-80e0-64569cd9b566.png)

**Comment by deeqakkk** [comment]
> ### What?
> I was reading the documentation of repo, and found a typo in the it.
> 
> ### Why?
> It should be fixed because it typo might create or reduce the trust that users have on the protocol along with authenticity.
> 
> ### How?
> It can be simply fixed by simplying changing a word with correct grammar.
> 
> ### Screenshot
> ![image](https://user-images.githubusercontent.com/78724676/219909163-a987aa45-c5c7-421f-80e0-64569cd9b566.png)

I would be happy if you can assign this issue to me. Thank you.

**Comment by utkars3** [comment]
@ravi-prakash-v  I want to work on this issue.Please assign it to me.

**Comment by ravi-prakash-v** [comment]
@deeqakkk assigned issue to you. Thanks for noticing the typo

**Comment by emmayank** [comment]
Hi @ravi-prakash-v , the PR has been raised for the above issue. Please find it here - https://github.com/beckn/protocol-specifications/pull/386
