### ISSUE TITLE
Errors in transaction.yaml core-v1.0.0

### ISSUE THREAD

**Issue by Rishabh-ondc** [beckn/protocol-specifications#350]
---

Name: Protocol Specifications
Title: "Errors in transaction.yaml core-v1.0.0"
Labels: C4GT Community

---

## Description

Please find below errors observed in transaction.yaml for released version core-v1.0.0

-Structural error at paths./rating.post.requestBody.content.application/json.schema.properties.message.properties.ratings.items
should be object

-Semantic error at paths./rating.post.requestBody.content.application/json.schema.properties.message.properties.ratings.items
'items' must be an object

-Structural error at components.schemas.Person.properties.age.allOf
should be array

-Structural error at components.schemas.ReturnTerm.properties.return_location
should NOT have additional properties
additionalProperty: desription

-Structural error at components.schemas.XInput.properties.form_submission
should NOT have additional properties
additionalProperty: data

Screenshot
<img width="459" alt="Transaction yaml error details" src="https://user-images.githubusercontent.com/109668555/228256151-063bc688-6f56-4bb4-b1ab-c7060079543c.png">

## Goals

- Find and fix errors observed in transaction.yaml for released version core-v1.0.0

## Expected Outcome

- Error Fix

---

### Project

Beckn

### Organization Name:

Beckn Open Collective

### Domain

Others

### Tech Skills Needed:

Open API 3.0
Beckn protocol

### Mentor(s)

Ravi Prakash

### Complexity

Medium

### Category

Bug

### Sub Category

Needs Reproduction

**Comment by emmayank** [comment]
Hi @ravi-prakash-v , the PR has been raised for the above issue. Please find it here - https://github.com/beckn/protocol-specifications/pull/386

**Comment by emmayank** [comment]
Closing this issue, as it is fixed as part of #386
