### ISSUE TITLE
Errors in meta.yaml core ver 1.0.0

### ISSUE THREAD

**Issue by faizmagic** [beckn/protocol-specifications#354]
---

Name: Protocol Specifications
Title: "Errors in meta.yaml core ver 1.0.0"
Labels: C4GT Community

---

## Description

meta.yaml file is giving the following error is swagger. needs to be corrected.

attached is the screenshot for reference.
![image](https://user-images.githubusercontent.com/3881432/231745406-6e5c20f2-dab8-4720-868a-0faf222321c3.png)

## Goals

- Bug Fix

## Expected Outcome

- Bug Fix

---

### Project

Beckn

### Organization Name:

Beckn Open Collective

### Domain

Others

### Tech Skills Needed:

Open API 3.0
Beckn protocol

### Mentor(s)

Ravi Prakash

### Complexity

Low

### Category

Bug

### Sub Category

Reproducible

**Comment by emmayank** [comment]
Hi @ravi-prakash-v , the PR has been raised for the above issue. Please find it here - https://github.com/beckn/protocol-specifications/pull/386
