### ISSUE TITLE
Support for multiple providers in a single order

### ISSUE THREAD

**Issue by vbabuEM** [beckn/protocol-specifications#402]
**Is your feature request related to a problem? Please describe.**
Currently the Order object in the Beckn spec has a single provider object. This limits the items that can be added to the order to a single Provider(seller). This is restrictive for multi-seller setups (e.g. setups like amazon, etsy etc). 

**Describe the solution you'd like**
Order object, just like the catalog object should support multiple providers.

**Describe alternatives you've considered**
BAP will currently have to split an order into multiple orders even if it is the same BPP. 

**Additional context**
Search operation supports searching multiple BPPs and multiple providers within single BPP. Once the order is created, restricting the order to be to a single BPP seems reasonable. Restricting order to a single provider(seller) seems excessively restrictive.

**Comment by venkatramanm** [comment]
Every seller-location needs an order for fulfillment and communication back and forth would be needed for the same. 

Some one has to split the orders by provider location. 

Bap any way needs to split by bpps. 

So the logic to split by location is a simple extension on the bap side. 


Communication of exceptions would become complex if the seller order is hidden from the bap.? 


Even if multiple sellers were possible in a single order., there will be multiple deliveries and communication / refunds /... would get more complicated. 


Hence this simplification. Which manages all the usecases with a simpler api.

**Comment by vbabuEM** [comment]
This is not an issue. More of a discussion. I will post one in the discussion forum. Closing this issue.
