### ISSUE TITLE
Validating Mobility Specification with Core v 1.1.0

### ISSUE THREAD

**Issue by viraj89** [beckn/protocol-specifications#423]
## Description
Validate the mobility.yaml file with the core-spec v1.1.0 version. Also, validate the examples JSON files given in the example directory and in the implementation guide against core-spec v1.1.0.

## Goals
- [x] Validate mobility.yaml with core-spec v1.1.0.
- [x] Validate the examples in the mobility domain repository against core-spec v1.1.0.
- [x] Validate the examples used in the implementation guide against core-spec v1.1.0.

## Sub Tasks
a. Validate mobility.yaml with core-spec v1.1.0.
b. Validate the examples in the mobility domain repository against core-spec v1.1.0.
c. Validate the examples used in the implementation guide against core-spec v1.1.0.

## Expected Outcome
The mobility.yaml file, examples in the mobility domain repository, and examples used in the implementation guide should pass validation against core-spec v1.1.0.

## Acceptance Criteria
- [x] mobility.yaml passes validation with core-spec v1.1.0.
- [x] Examples in the mobility domain repository pass validation against core-spec v1.1.0.
- [ ] Examples used in the implementation guide pass validation against core-spec v1.1.0.

## Product Name
Beckn

## Domain
Mobility

## Tech Skills Needed
Spec validation tools, YAML, JSON

## Complexity
Medium

## Category
Validation

## Sub Category
Spec Compliance

**Comment by emmayank** [comment]
Task is completed and PR is raised here - https://github.com/beckn/mobility/pull/76
