### ISSUE TITLE
Using HTTP codes for error responses

### ISSUE THREAD

**Issue by pkapustin** [beckn/protocol-specifications#44]
According to the specification, errors are currently returned with HTTP code 200 OK.

We should use other HTTP codes for error responses to comply with the standard. This will also allow to simplify the response body, as then having the message field with ACK/NACK status should no longer be necessary.

**Comment by beckn-dev** [comment]
Beckn protocol is designed to be transport protocol agnostic. Hence adding more HTTP codes will lock the protocol to be only HTTP compliant. Hence the 200 OK for all responses.
