### ISSUE TITLE
Ability to pass dynamic fields

### ISSUE THREAD

**Issue by Viv3kshukla** [beckn/protocol-specifications#49]
Can the spec have some mechanism to pass dynamic fields? This would help BPP implementation to not limit itself on the spec for describing entities (example: provider-specific metadata). Maybe adding key-value array in Descriptor type.

**Comment by beckn-dev** [comment]
Can you give an example of the same ?

**Comment by Viv3kshukla** [comment]
For example: So for mobility on_search catalog, a BPP/organization/brand along with returning list of offered items, wants to send some statistics like how many rides they have completed up till now, their average product/service rating, etc. (could be more of these)
Do we have some mechanism to send this information to BAP?

**Comment by beckn-dev** [comment]
The `Tag` schema should take care of that now. It is present as a subschema in various schema like `Item`, `Catalog`, `Descriptor` etc. It can be used to send any additional data that is not captured in the standard schema.
