### ISSUE TITLE
Why Open API 3.0 or similar structure not used to define the specifications?

### ISSUE THREAD

**Issue by fahadsuhaib** [beckn/protocol-specifications#53]
Hello, I think the protocol is great, but can there be some discussion on why some standard structure was not used? I would say Open API spec would have provided a great tooling behind the protocol, so any1 can start working on either Provider or Apps side of the story.

Would love you hear your views.

**Comment by beckn-dev** [comment]
We _are_ using Open API 3.0 specification to describe our APIs. While Open API 3.0's default format is YAML, we used JSON in the beginning. Now it has YAML as well. 

Please refer to https://github.com/beckn/protocol-specifications/blob/master/core/v0/api/core.yaml to view the latest version.
