### ISSUE TITLE
Use protocol buffer to define the API specification

### ISSUE THREAD

**Issue by chinmayb** [beckn/protocol-specifications#64]
All it takes is to define the proto, using that to we can easily generate the [OpenAPI](https://github.com/OAI/OpenAPI-Specification) specification which will be the source to generate interactive API documentation, SDK clients etc.

The existing API structures can be easily migrated to proto and the client SDKs and managed well in the future. 
https://github.com/beckn/protocol-specifications/blob/master/core/v0/api/core.json

[Protocol buffers](https://developers.google.com/protocol-buffers)

**Comment by beckn-dev** [comment]
There have been multiple requests to do the same. We shall definitely consider them in upcoming releases.

**Comment by chinmayb** [comment]
Let me know if you'd need any help in that regard.

**Comment by beckn-dev** [comment]
If you can create a PR for the same, that would be great.
